### ISSUE TITLE
endogenous genomic sequences

### ISSUE THREAD

**Issue by yeroslaviz** [menggf/transgeneR#1]
Hi, I found your tools after a long search of efficient ways to analyze this kind of data.

I have also read the paper with great interest and will definitely try the package. 
But beforehand I have one question (for now :-) ) after reading the methods part of the paper.

in 2.3 you mentioned that reads with mapping results in both the transgene and the genome were marked as possible insertion sites. But what if the transgene already contains endogenous sequence in itself? can the package handle this kind of analysis?

My transgene contains at one end a snippet from chr12 and on the other end a snippet from chr17. But we don't think it integrates in these two chromosomes. Can the tool compensate for this kind of arrangement? 

I have tried already [gridss](https://github.com/PapenfussLab/gridss), if you know it, which didn't gives me absolute results. But for that analysis I have masked the regions on chr12 and 17 which are also in the transgene. Is this necessary also here?

thanks
Assa

**Comment by yeroslaviz** [comment]
Ok, I have read the rest of the paper and understood how you compensate for that factor.

my question is still the same. It is better to mask the regions common to the transgene and the genome (e.g. convert them to NNNNNNNN...) or would it be better to leave them in their original form?

**Comment by menggf** [comment]
Thanks for your interest and also sorry for a late reply. It will be more efficient for email if you need further supporting.
For the regions common to the transgene and the genome , transgeneR has the codes to judge its origin based one the sequencing information, e.g. mapping scores. This usually works, especially when the homologous region is from different species. In case, it fails to find any difference in both genome and transgene, transgeneR will assign it to transgene. This is usually true when the chance to observe an integration/rearrange event in homologous region of genome is very low.
