### ISSUE TITLE
what to do with the results?

### ISSUE THREAD

**Issue by yeroslaviz** [menggf/transgeneR#4]
Hi again,

is this repository still maintained?

I have done the analysis and got the results. I have one pdf file with the fragment, where multiple chromosomes show a possible insertion. How do I pin-point the insertion sites?
In the `sites` folder I have over 2500 plots. I can see an easy way to find possible pairs (with that I mean the two plots which would point to a possible insertion site, containing the "chr <- insertion" and " insertion -> chr").

The report file contains 21304 sites, the `sites` folder has "only" 2556 plots. why the different numbers? which sites are not plotted?

Even though the tool works very nicely and it seems to be a very good tool, I think quite a lot needs to be improved. A better explanation of the results is of special importance in my opinion.

**Comment by menggf** [comment]
The issue for number difference of sites and plots is that transgeneR will filter some low quality sites before it made plots. 

Thanks for your suggestion. I can update its document later.
